"""New link fields

Revision ID: 019c3ac1e62d
Revises: 7309f223030c
Create Date: 2021-08-21 13:37:29.838930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019c3ac1e62d'
down_revision = '7309f223030c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('header', sa.Boolean(), nullable=True))
    op.add_column('link', sa.Column('space', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'space')
    op.drop_column('link', 'header')
    # ### end Alembic commands ###
